package ss.nscube.webshare.core.server.repo.item

object MimeTypes: HashMap<String, String>() {

    const val OctetStream =  "application/octet-stream"
    const val JsonMimeType =  "application/json"

    init {
        this["epub"] = "application/epub+zip"
        this["gz"] = "application/gzip"
        this["jar"] = "application/java-archive"
        this["ser"] = "application/java-serialized-object"
        this["class"] = "application/java-vm"
        this["js"] = "application/javascript"
        this["json"] = "application/json"
        this["doc"] = "application/msword"
        this["dot"] = "application/msword"
        this["bin"] = "application/octet-stream"
        this["deploy"] = "application/octet-stream"
        this["msu"] = "application/octet-stream"
        this["msp"] = "application/octet-stream"
        this["pdf"] = "application/pdf"
        this["prf"] = "application/pics-rules"
        this["xhtml"] = "application/xhtml+xml"
        this["xht"] = "application/xhtml+xml"
        this["xml"] = "application/xml"
        this["xsd"] = "application/xml"
        this["xsl"] = "application/xslt+xml"
        this["xslt"] = "application/xslt+xml"
        this["xspf"] = "application/xspf+xml"
        this["zip"] = "application/zip"
        this["apk"] = "application/octet-stream"
        this["deb"] = "application/vnd.debian.binary-package"
        this["ddeb"] = "application/vnd.debian.binary-package"
        this["udeb"] = "application/vnd.debian.binary-package"
        this["torrent"] = "application/x-bittorrent"
        this["7z"] = "application/x-7z-compressed"
        this["info"] = "application/x-info"
        this["jnlp"] = "application/x-java-jnlp-file"
        this["m3u8"] = "application/x-mpegURL"
        this["tar"] = "application/x-tar"
        this["aac"] = "audio/aac"
        this["flac"] = "audio/flac"
        this["mid"] = "audio/midi"
        this["midi"] = "audio/midi"
        this["kar"] = "audio/midi"
        this["mpga"] = "audio/mpeg"
        this["mpega"] = "audio/mpeg"
        this["mp2"] = "audio/mpeg"
        this["mp3"] = "audio/mpeg"
        this["m4a"] = "audio/mpeg"
        this["m3u"] = "audio/mpegurl"
        this["oga"] = "audio/ogg"
        this["ogg"] = "audio/ogg"
        this["opus"] = "audio/ogg"
        this["spx"] = "audio/ogg"
        this["wav"] = "audio/x-wav"
        this["ttc"] = "font/collection"
        this["otf"] = "font/otf"
        this["ttf"] = "font/ttf"
        this["woff"] = "font/woff"
        this["woff2"] = "font/woff2"
        this["gif"] = "image/gif"
        this["ief"] = "image/ief"
        this["jp2"] = "image/jp2"
        this["jpg2"] = "image/jp2"
        this["jpeg"] = "image/jpeg"
        this["jpg"] = "image/jpeg"
        this["jpe"] = "image/jpeg"
        this["jpm"] = "image/jpm"
        this["jpx"] = "image/jpx"
        this["jpf"] = "image/jpx"
        this["pcx"] = "image/pcx"
        this["png"] = "image/png"
        this["svg"] = "image/svg+xml"
        this["svgz"] = "image/svg+xml"
        this["tiff"] = "image/tiff"
        this["tif"] = "image/tiff"
        this["css"] = "text/css"
        this["html"] = "text/html"
        this["htm"] = "text/html"
        this["shtml"] = "text/html"
        this["asc"] = "text/plain"
        this["txt"] = "text/plain"
        this["text"] = "text/plain"
        this["pot"] = "text/plain"
        this["brf"] = "text/plain"
        this["srt"] = "text/plain"
        this["h++"] = "text/x-c++hdr"
        this["hpp"] = "text/x-c++hdr"
        this["hxx"] = "text/x-c++hdr"
        this["hh"] = "text/x-c++hdr"
        this["c++"] = "text/x-c++src"
        this["cpp"] = "text/x-c++src"
        this["cxx"] = "text/x-c++src"
        this["cc"] = "text/x-c++src"
        this["h"] = "text/x-chdr"
        this["htc"] = "text/x-component"
        this["csh"] = "text/x-csh"
        this["c"] = "text/x-csrc"
        this["d"] = "text/x-dsrc"
        this["diff"] = "text/x-diff"
        this["patch"] = "text/x-diff"
        this["hs"] = "text/x-haskell"
        this["java"] = "text/x-java"
        this["ly"] = "text/x-lilypond"
        this["lhs"] = "text/x-literate-haskell"
        this["py"] = "text/x-python"
        this["sh"] = "text/x-shellscript"
        this["scala"] = "text/x-scala"
        this["mp4"] = "video/mp4"
        this["qt"] = "video/quicktime"
        this["mov"] = "video/quicktime"
        this["mpeg"] = "video/mpeg"
        this["mpg"] = "video/mpeg"
        this["mpe"] = "video/mpeg"
        this["webm"] = "video/webm"
        this["mpv"] = "video/x-matroska"
        this["mkv"] = "video/x-matroska"
        this["avi"] = "video/x-msvideo"
    }

    override operator fun get(key: String): String {
        return super.get(key) ?: OctetStream
    }
}